[build]
  publish = "external-production"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/welcome"
  to = "/welcome.html"
  status = 200

[[redirects]]
  from = "/nda-request"
  to = "/nda-request.html"
  status = 200
